# action.yml
name: 'Get repo files tree'
description: 'Get repo files tree'
inputs:
  accessToken:  # id of input
    description: 'Github Token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.accessToken }}
